---
src_vocab: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/vocab.bpe.32000'
dst_vocab: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/vocab.bpe.32000'
src_vocab_size_a: 32000
dst_vocab_size_a: 32000
src_vocab_size_b: 32000
dst_vocab_size_b: 32000
hidden_units: 512
scale_embedding: True
attention_dropout_rate: 0.0
residual_dropout_rate: 0.1
num_blocks: 6
num_heads: 8
binding_embedding: False
kl_weight: 0.0
enc_layer_indep: 4
enc_layer_share: 1
dec_layer_indep: 4
dec_layer_share: 1
generate_maxlen: 50
lock_enc_embed: True
multi_channel_encoder: True
gan_iter_num: 888
gan_gen_iter_num: 1
gan_dis_iter_num: 1
generate_num: 5000
rollnum: 20
bias_num: 0.3
logdir: './gan.log'

train:
    devices: '0'
    src_path: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/train.tok.bpe.clean.32000.lf.50.en.shuf.mono'
    dst_path: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/train.tok.bpe.clean.32000.lf.50.de.shuf.mono'
    tokens_per_batch:  25000
    max_length: 50
    num_epochs: 500
    logdir: 'gan.log'
    save_freq: 1000
    summary_freq: 100
    grads_clip: 5
    optimizer: 'adam_decay'
    learning_rate: 0.00005
    gan_learning_rate: 0.00001
    learning_rate_warmup_steps: 4000
    label_smoothing: 0.1
    batch_size: 250
    shared_embedding: False

generator:
    src_vocab: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/vocab.bpe.32000'
    dst_vocab: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/vocab.bpe.32000'
    devices: '0,1'
    src_path: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/train.tok.bpe.clean.32000.lf.50.en.shuf.mono'
    dst_path: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/train.tok.bpe.clean.32000.lf.50.de.shuf.mono'
    tokens_per_batch:  25000
    max_length: 50
    num_epochs: 500
    logdir: 'gan.log'
    save_freq: 1000
    summary_freq: 100
    grads_clip: 5
    optimizer: 'rmsprop'
    modelFile: '/home/user/zy/experience/unSupervisedNMT/ai_challenger/gan_training/model_epoch_1_step_307000'
    learning_rate: 0.00001
    gan_learning_rate: 0.00001
    learning_rate_warmup_steps: 4000
    label_smoothing: 0.1
    batch_size: 100

discriminator:
    dis_src_vocab: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/vocab.bpe.32000.pkl'
    dis_dst_vocab: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/vocab.bpe.32000.pkl'
    dis_max_epoches: 888
    dis_dispFreq: 1
    dis_saveFreq: 100
    dis_devFreq: 100
    dis_batch_size: 40
    dis_saveto: '../experience/unSupervisedNMT/ai_challenger/gan_training/dis_mono'
    dis_reshuffle: False
    dis_gpu_devices: 'gpu-2-3-4-5'
    dis_max_len: 50
    s_domain_data: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/s_domain_data'
    t_domain_data: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/t_domain_data'
    s_domain_generated_data: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/s_domain_generated_data'
    t_domain_generated_data: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/t_domain_generated_data'
    dev_s_domain_data: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/dev_s_domain_data'
    dev_t_domain_data: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/dev_t_domain_data'
    dev_s_domain_generated_data: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/dev_s_domain_generated_data'
    dev_t_domain_generated_data: '/home/user/zy/dl4mt/corpus/lf_50_for_unsupervised_NMT/data_for_gan_training/dev_t_domain_generated_data'
    dis_reload: True
    dis_clip_c: 1.0
    dis_dim_word: 512
    dis_optimizer: 'rmsprop'
    dis_scope: 'discnn'

test:
    mode: 'ab'
    src_path: './bleuTest/newstest2016/newstest2016.tok.bpe.32000.en'
    dst_path: './bleuTest/newstest2016/newstest2016.tok.bpe.32000.de'
    ori_dst_path: './bleuTest/newstest2016/newstest2016.tok.de'
    output_path: './bleuTest/newstest2016/newstest2016.ab.output'
    batch_size: 256
    max_target_length: 200
    beam_size: 4
    lp_alpha: 0.6
    devices: '0,1'
    modelFile: '/home/user/zy/experience/unSupervisedNMT/ai_challenger/gan_training/model_epoch_1_step_307000'
